title: *Indego Shared Bike Demand Forecast*
logo: /assets/img/logo.png
description: CIS 545 Final Project, Spring 2023
show_downloads: false
repository: MUSA-550-Fall-2021/github-pages-single-page-starter
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
