title: Final Project
logo: /assets/img/indego.png
description: CIS545 Big Data Analytics, Spring 2023
show_downloads: false
repository: MUSA-550-Fall-2021/github-pages-single-page-starter
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
